### ISSUE TITLE
Add Rasor motors into devices

### ISSUE THREAD

**Issue by Relm-Arrowny** [Relm-Arrowny/i10-bluesky#4]
### Goals
- [ ]  User should be able to move Rasor motors  within bluesky/blueapi
       1. Move means they should be able to do both flying scan and step scan.
       2. Move them on its own or as a group of motors. 

- [ ]  Devices limit should be respected and handled correctly (both hard and soft).
         1. soft limit should be checked before move.
         2. hard limit, possible options:
                  -  stop all device displace warning and end all queued actions
                  -  stop current device, displace warning and continue queued actions         

- [x] #5
### Tasks
- [x] #7
- [ ] Create devices using [ophyd-async](https://github.com/bluesky/ophyd-async)

**Comment by Relm-Arrowny** [comment]
Done and live in [dodal](https://github.com/DiamondLightSource/dodal/pull/879)
