### ISSUE TITLE
Create device for the two clean up slits and scaler card, create a plan to do fly scan and step scan.

### ISSUE THREAD

**Issue by Relm-Arrowny** [Relm-Arrowny/i10-bluesky#9]
### Goals
- [x]  Add the two clean up slits and scaler card using ophyd_ascync
       1.  All motor should be flyable type.
       2.  All detector should should auto scale/gain 
       3. Should also have sim mode to test logic

### Tasks
- [x]  Make detector slits device
- [x]  Make scaler card into device
- [x]  Dynamically change current amplifier gain  
- [x]  putting everything together to perform detector slits scans.
- [x]  Auto alignment of slits.

**Comment by Relm-Arrowny** [comment]
devices are now all in dodal rather than here, and this is linked to https://github.com/DiamondLightSource/dodal/issues/811

**Comment by Relm-Arrowny** [comment]
To my surprise, it seem to work first try running it in blueapi,  but need to look into some errors:
Not sure if invalid type float65 is an issue, also the e-18 current seem too small may need to check with beam. 
![image](https://github.com/user-attachments/assets/448ce3b9-af09-4bea-8619-6efad1e09a7e)
